version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo pre build started on `date`
      - echo TWITCH_MS_IMAGE_TAG
      - echo %TWITCH_MS_IMAGE_TAG%
      - echo SPRING_CODE_ARTIFACT_PATH
      - echo %SPRING_CODE_ARTIFACT_PATH%
      - echo pre build started on `date`
      - npm install -g aws-cdk
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile
      - cdk synth
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - cdk.out/EksCdkStack.template.json